"""initial schema: users, servers, shared_access

Revision ID: e6464d47a6c5
Revises: 
Create Date: 2026-08-29 09:32:10.083510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6464d47a6c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('credit_balance', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('credit_balance >= 0', name=op.f('ck_users_credit_balance_non_negative')),
    sa.CheckConstraint('length(username) >= 3', name=op.f('ck_users_username_min_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('ram_tier', sa.Integer(), nullable=False),
    sa.Column('pterodactyl_server_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'installing', 'running', 'stopped', 'suspended', 'error', 'deleting')", name=op.f('ck_servers_status_known')),
    sa.CheckConstraint('ram_tier IN (1, 2, 3, 4)', name=op.f('ck_servers_ram_tier_known')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_servers_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers')),
    sa.UniqueConstraint('owner_id', 'name', name='uq_servers_owner_id_name')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_pterodactyl_server_id'), ['pterodactyl_server_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_servers_status'), ['status'], unique=False)

    op.create_table('shared_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('guest_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guest_user_id'], ['users.id'], name=op.f('fk_shared_access_guest_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_shared_access_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_access')),
    sa.UniqueConstraint('server_id', 'guest_user_id', name='uq_shared_access_server_guest')
    )
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_access_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_shared_access_guest_user_id', ['guest_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_access_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_access_server_id'))
        batch_op.drop_index('ix_shared_access_guest_user_id')
        batch_op.drop_index(batch_op.f('ix_shared_access_created_at'))

    op.drop_table('shared_access')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_status'))
        batch_op.drop_index(batch_op.f('ix_servers_pterodactyl_server_id'))
        batch_op.drop_index(batch_op.f('ix_servers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_servers_created_at'))

    op.drop_table('servers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
